#ifndef _QA_DEFINE_H_
#define _QA_DEFINE_H_

#define TARGET_WEATHER 			"TARGET_WEATHER"
#define TARGET_NO_AREA 			"TARGET_NO_AREA"
#define TARGET_TEMPERATURE 		"TARGET_TEMPERATURE"
#define TARGET_IS_COLD 			"TARGET_IS_COLD"
#define TARGET_IS_HOT 			"TARGET_IS_HOT"
#define TARGET_IS_RAINY 		"TARGET_IS_RAINY"
#define TARGET_IS_SNOWY 		"TARGET_IS_SNOWY"
#define TARGET_IS_WINDY 		"TARGET_IS_WINDY"
#define TARGET_IS_TYPHOON 		"TARGET_IS_TYPHOON"
#define TARGET_TYPHOON 			"TARGET_TYPHOON"
#define TARGET_INDEX 			"TARGET_INDEX"

#define FIELD_DATE 		"daytime"
#define FIELD_AREA 		"cityname"
#define FIELD_INDEX 	"index"


#define SECOND_IN_ONE_DAY 		86400

#endif
